/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.climbsafe.application;

import java.sql.Date;

import ca.mcgill.ecse.climbsafe.model.*;

public class ClimbSafeApplication {
	
	private static ClimbSafe climbSafe = null;
	
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new ClimbSafeApplication().getGreeting());
    }
    
    public static ClimbSafe getClimbSafe() {
    	if( climbSafe == null ) {
    		@SuppressWarnings("deprecation")
			Date defaultDate = new Date(0, 0, 0);
    		climbSafe = new ClimbSafe(defaultDate, 0, 0);
    	}
    	return climbSafe;
    }
}
