/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.climbsafe.application;

import ca.mcgill.ecse.climbsafe.model.*;
import ca.mcgill.ecse.climbsafe.view.*;
import ca.mcgill.ecse.climbsafe.persistence.ClimbSafePersistence;

public class ClimbSafeApplication {
  private static ClimbSafe climbSafe = null;

  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(new ClimbSafeApplication().getGreeting());
    climbSafe = getClimbSafe();
    if( climbSafe.getAdministrator() == null ) {
    	new Administrator("admin@nmc.nt", "admin", climbSafe);
    	ClimbSafePersistence.save();
    }
    ClimbSafeGUI gui = new ClimbSafeGUI();
  }

  public static ClimbSafe getClimbSafe() {
	  if( climbSafe == null ) {
		  climbSafe = ClimbSafePersistence.load();  
	  }
	  return climbSafe;
  }
}
