/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.climbsafe.application;

import java.sql.Date;
import ca.mcgill.ecse.climbsafe.model.*;
import ca.mcgill.ecse.climbsafe.persistence.ClimbSafePersistence;
import ca.mcgill.ecse.climbsafe.controller.*;

public class ClimbSafeApplication {
  private static ClimbSafe climbSafe = null;

  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(new ClimbSafeApplication().getGreeting());
    climbSafe = getClimbSafe();
    climbSafe.delete();
    ClimbSafePersistence.save();  
  }

  public static ClimbSafe getClimbSafe() {
	  if( climbSafe == null ) {
		  climbSafe = ClimbSafePersistence.load();  
	  }
	  return climbSafe;
  }
}
